"""add_personal_profile_tables

Revision ID: aebeb8e67477
Revises: b0b886ef0f41
Create Date: 2025-12-02 23:05:19.850281+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aebeb8e67477'
down_revision: Union[str, None] = 'b0b886ef0f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'account_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'account_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'corporate'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
