"""Add Company model and extend User model for Phase 1

Revision ID: b0b886ef0f41
Revises: 20251202_000000
Create Date: 2025-12-02 22:27:48.434875+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b886ef0f41'
down_revision: Union[str, None] = '20251202_000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Note: companies table already exists from Phase 0 initial schema
    # Only adding columns to users table for Phase 1

    # Add columns to users table with server_default for existing rows
    op.add_column('users', sa.Column('account_type', sa.String(length=20), nullable=False, server_default='corporate'))
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('parent_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_account_type'), 'users', ['account_type'], unique=False)
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_foreign_key('fk_users_parent_user_id', 'users', 'users', ['parent_user_id'], ['id'])
    op.create_foreign_key('fk_users_company_id', 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop foreign keys and columns from users
    op.drop_constraint('fk_users_company_id', 'users', type_='foreignkey')
    op.drop_constraint('fk_users_parent_user_id', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_index(op.f('ix_users_account_type'), table_name='users')
    op.drop_column('users', 'parent_user_id')
    op.drop_column('users', 'company_id')
    op.drop_column('users', 'account_type')

    # Note: companies table is not dropped as it was created in Phase 0 initial schema
    # ### end Alembic commands ###
