"""Add PersonCorporateContract DataSharingSettings SyncLog tables

Revision ID: 59a3d3577f9d
Revises: aebeb8e67477
Create Date: 2025-12-02 23:34:20.700482+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a3d3577f9d'
down_revision: Union[str, None] = 'aebeb8e67477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
